version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: mysql:8.0.34
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todoDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./create_this.sql:/docker-entrypoint-initdb.d/create_this.sql

